name: ğŸ”¨ğŸ§ª Build & Test

permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on: [push]

jobs:
  testAndCoverageFront:
    name: ğŸ“± Build & Test App
    uses: ./.github/workflows/_build_front.yml
    secrets: inherit

  testAndCoverageBack:
    name: ğŸ‘½ï¸ Test & Coverage
    uses: ./.github/workflows/_build_back.yml
    secrets: inherit
